### ISSUE TITLE
Feat: Allow PODs to access storage resources by using persistent volume claims as volume

### ISSUE THREAD

**Issue by GiovanniMancini** [pagopa/aks-microservice-chart-blueprint#110]
A `PersistentVolumeClaim` (PVC) is a storage request. It is similar to a pod. Pods consume node resources while PVCs consume persistent volume resources. When the PVC requests special `StorageClasses`, the cluster can dynamically provision a volume for the PVC. **Pods access the provisioned storage by using the claim as a volume**, as shown here

```
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
      volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume
          readOnly: false
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk
```

Claims must exist in the same namespace as the Pod using the claim. The cluster finds the claim in the Pod's namespace and uses it to get the `PersistentVolume` backing the claim. The volume is then mounted to the host and into the Pod.

I believe it would be extremely helpful for a variety of use cases to include in the blueprint the possibility of mounting the PVC as a volume.

Refs
[Persistent volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)
[Claims as volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes)
[PVC for  Azure Disks](https://learn.microsoft.com/en-us/azure/aks/azure-csi-disk-storage-provision)
[PVC for Azure Storage](https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-provision?tabs=mount-nfs%2Csecret)
