### ISSUE TITLE
canaryDelivery created ingress for blue/green (path based)

### ISSUE THREAD

**Issue by pietro-tota** [pagopa/aks-microservice-chart-blueprint#136]
Hi, I was configuring a blue/green deployment for an [eCommerce service](https://github.com/pagopa/pagopa-notifications-service) and found this strange template behavior (using template version 7.3.1, seems to be the same with main version).

The desiderata here is to replicate what the 2.x template does for blue/green deploy that is create an ingress with a `/beta` prefix

I set  this configuration for canary deployment: 
```yaml
  canaryDelivery:
    create: true
    ingress:
      bluegreen: true
      header: false
      weightPercent: 0
```
and the following ingress is produced:
```yaml
---
# Source: pagopa-notifications-service/charts/microservice-chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-microservice-chart
  namespace: ecommerce
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/canary: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: weuuat.ecommerce.internal.uat.platform.pagopa.it
      http:
        paths:
          - backend:
              service:
                name: release-name-microservice-chart
                port:
                  number: 3000
            path: /beta/pagopa-notifications-service/(.*)
            pathType: ImplementationSpecific
  tls:
    - hosts: [weuuat.ecommerce.internal.uat.platform.pagopa.it]
      secretName: weuuat-ecommerce-internal-uat-platform-pagopa-it
---
```
Using this ingress configuration in the cluster result in a 404 to be returned by nginx while invoke the endpoint `https://weuuat.ecommerce.internal.uat.platform.pagopa.it/beta/pagopa-notifications-service/...`

The problem here seems to be that there are both configured:
- `nginx.ingress.kubernetes.io/canary: "true"` annotation set to true -> this is not expected and is the root cause for the 404
-  the ingress path with the `/beta` prefix -> this is expected

The root cause is the label canary that is set to true and with this configuration nginx cannot found another ingress with same path (and disabled canary annotation) starting with /beta, causing the 404.
Set the annotation to false the ingress starts to work properly forwarding requests to the correct pod in the cluster.
As a workaround I'm performing blue/green deployment with the following configuration:
```yaml
  canaryDelivery:
    create: true
    ingress:
      bluegreen: false
      #set canary deployment with traffic balancing see https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#canary for more info
      header: true
      headerName: deployment
      headerValue: blue
      weightPercent: 0
```
switching from a path to a header based routing for blue/green api calls (another way could be use an explicit ingress path override).
Can you separate the configuration to enable the nginx [canary](https://github.com/pagopa/aks-microservice-chart-blueprint/blob/6a8260c7e0ca85491860d563e5a625a46d1e45d4/charts/microservice-chart/templates/ingress.yaml#L15-L17) feature from the [bluegreen](https://github.com/pagopa/aks-microservice-chart-blueprint/blob/6a8260c7e0ca85491860d563e5a625a46d1e45d4/charts/microservice-chart/templates/ingress.yaml#L36-L38) path prefix parameter?
