### ISSUE TITLE
deployment v3.0.0 - invalid value for selector

### ISSUE THREAD

**Issue by and-mora** [pagopa/aks-microservice-chart-blueprint#90]
Hi, I updated rtd-ms-decrypter (PR [here](https://github.com/pagopa/rtd-ms-decrypter/pull/99)) from microservice-chart-2.0.0 to the latest microservice-chart-3.0.0 but encountered 2 errors. 

The first one on the `helm dependency build` deploy pipeline step. 
```
##[error]Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies
```
complete log [here.](https://dev.azure.com/pagopaspa/cstar-platform-app-projects/_build/results?buildId=85670&view=logs&j=165c5811-b3e6-591b-ec8e-64a94992e27b&t=9dbbf757-31f7-5995-6e9e-42444ffe4854)

I fixed it by running `helm dependency build` and adding the `Chart.lock` file in the helm directory. Is that the correct fix? The chart.lock file is not required till microservice-chart-2.8.0.

The second error I've encountered is in the helm upgrade deploy pipeline step:
```
Error: UPGRADE FAILED: cannot patch "rtd-ms-decrypter-microservice-chart" with kind Deployment: Deployment.apps "rtd-ms-decrypter-microservice-chart" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"rtd-ms-decrypter", "app.kubernetes.io/name":"microservice-chart"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
complete log [here.](https://dev.azure.com/pagopaspa/cstar-platform-app-projects/_build/results?buildId=85682&view=logs&j=165c5811-b3e6-591b-ec8e-64a94992e27b&t=d4b593ca-e5c4-54f8-2d72-aacccc5f334a)

Exploring the code it looks like the `deployment` selector is missing from the `aks-microservice-chart-blueprint/charts/microservice-chart/values.yaml` file:
```
# -- Configure deployment
# @default -- -
replicas: 1
# -- (bool) Force redeploy container
forceRedeploy: false
ports:
  - 8080
```
does it make sense to you? code reference [here](https://github.com/pagopa/aks-microservice-chart-blueprint/blob/38e0f3fc10e524c823f9c5f562200685da526b0d/charts/microservice-chart/values.yaml#L158)

Microservice config
`values-dev.yaml`
```
  deployment:
    create: true
    replicas: 1
```
`Chart.yaml`
```
apiVersion: v2
name: rtdmsdecrypter
description: Micro-service designed to decrypt and split aggregate and transaction files.
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
```
